Tarea 1, Clase 6
Alfred021/introduccion-a-js pull request #6
Opened 2019-12-09 00:38 UTC by Alfred021

Tarea 1, clase 6
La hice pidiendo nada mas empezar la pagina el numero de integrantes.

2019-12-10 21:43 UTC, fsodano requested changes

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.html
> +        <button id='calcular' type ="button">Calcular</button>
se consistente con las comillas, usá `""` para html

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.html
> +    <form id="para-calcular-edades">
este nombre no me gusta. capaz sólo `calcular-edades` está mejor

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.html
> +</html>
acordate de dejar una línea vacía al final de cada archivo, github te avisa mostrándote el circulito rojo

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    }
esto está mal identado, debería estar a la altura de `let miembrosGrupoFamiliar` porque no está dentro de nada

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +function CrearMiembros(numero = 1) {
las funciones y variables no van con `PascalCase`, van con `camelCase`, es decir, `crearMiembros`.

En vez de número, yo le pondría `indice`!

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    let edades = SacarEdades ();
`sacar` es muy coloquial, lo que vos querés hacer es `obtenerEdadesMiembros`

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    document.querySelector('#mayor-edad').value = sacarmayorEdad ();
`calcularMayorEdad`

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    document.querySelector('#menor-edad').value = sacarmenorEdad ();
`calcularMenorEdad`

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    document.querySelector('#promedio-edad').value = sacarpromedioEdad(edades);
`calcularPromedioEdades`, lo que hiciste bien acá es pasar las edades como parámetros!  En los otros 2, estás obteniendo las edades de los miembros otra vez, es mejor que digas que las funciones `calcularMayorEdad` o `calcularMenorEdad` toman como parámetro un array de edades.

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    borrarPromedio ();
los paréntesis van justo después del nombre de la función: `borrarIntegrantes()`.

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +        acumulador + 1;
Acá no estás guardando el resultado de esta operación en ningún lado

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    label.textContent = 'Edad del integrante Nro: ' + (acumulador);
Este acumulador no te da siempre 1? Creo que simplemente podrías usar la variable `numero`, ya que estás pasando el nro del integrante como parámetro.

Imagino que lo que querés evitar es que diga `integrante nro 0`, en cuyo caso podés poner simplemente `'Edad del integrante nro: ' + (numero + 1)`

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    let mayorEdad = SacarEdades ();
`mayorEdad` va a contener un listado de edades... por lo tanto el nombre no está bien. El nombre sería `edades`o `edadesMiembros` o `listadoEdades`, pero no `mayorEdad`.

Por otro lado, sería mejor que tomes el listado de edades como parámetro.

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    let resultadomayorEdad = Math.max(...mayorEdad);
Esto está bien, pero te recomiendo que lo resuelvas con un `for` para pensarlo vos sólo.

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +    let contador = 0;
Esto sería un `acumulador`

2019-12-10 21:43 UTC, fsodano commented on tareas/clase-6/tarea 1, clase 6.js
> +function borrarnumMayor () {
bien, sólo fijate que las funciones sean `camelCase`. `borrarNumeroMayor`

2019-12-24 22:20 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.html
> +        <button id='calcular' type ="button">Calcular</button>
listo

2019-12-24 22:20 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.html
> +    <form id="para-calcular-edades">
listo

2019-12-24 22:21 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.html
> +</html>
listo

2019-12-24 22:21 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    }
listo

2019-12-24 22:21 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +function CrearMiembros(numero = 1) {
listo

2019-12-24 22:21 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    let edades = SacarEdades ();
listo

2019-12-24 22:21 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    document.querySelector('#mayor-edad').value = sacarmayorEdad ();
listo

2019-12-24 22:22 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    document.querySelector('#menor-edad').value = sacarmenorEdad ();
listo

2019-12-24 22:22 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    borrarPromedio ();
listo

2019-12-24 22:22 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +        acumulador + 1;
listo, lo cambie usando numero

2019-12-24 22:26 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    let mayorEdad = SacarEdades ();
listo

2019-12-24 22:26 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +    let contador = 0;
listo

2019-12-24 22:26 UTC, Alfred021 commented on tareas/clase-6/tarea 1, clase 6.js
> +function borrarnumMayor () {
listo

2019-12-24 23:40 UTC, merged